name: test-unreal-build

on: [push]

jobs:
  build-proyect:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v5

  
      - uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: 'C:/Unreal Engine/UE5.3_Source/Engine/Build/BatchFiles/RunUAT.bat'
          UPROJECT_PATH: ${{ github.workspace }}/ShowProject/ShowProject.uproject
          BUILD_CONFIG: Development
          PLATFORM: Win64
          CLEAN: true
          COOK: true
          STAGE: true
          PACKAGE: true
          PAK: false
          SERVER: false
          ARCHIVE: false
          ARCHIVE_PATH: 'C:/Archives/MyGame'
          NULLRHI: true
          EDITOR: false
          ENCRYPT_INI: true
          RELEASE: '1.0.0'
          PATCH: '0.0.0'
          MAPS: 'Map1,Map2'
          DELETE_PDB: true
          ANTICHEAT_ENABLED: false

      
